---

services:
  event_dispatcher:
    class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    arguments: ['@service_container']

  logger:
    class: Monolog\Logger
    arguments: ['logger']

  context_router:
    class: Steelbot\ContextRouter
    arguments: ['@service_container']
    calls:
      - [setLogger, ['@logger']]

  protocol:
    class: Steelbot\Protocol\Irc\Protocol
    arguments: ['@event_dispatcher']
    calls:
      - [setLogger, ['@logger']]
      - [setServer, ['127.0.0.1']]

